include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
    - "**/app_icons.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error